openapi: 3.0.1
info:
  title: potter
  version: 1beta
  contact:
    name: me
paths:
  /status:
    get:
      description: Return server stat
      operationId: app.get_status
      responses:
        "200":
          description: Server stats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'


  /restart:
    post:
      description: restart game
      operationId: app.post_restart
      responses:
        "200":
           description: Server status
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/Status'


  /user/{username}:
    post:
      description: create a new user
      operationId: app.post_user
      parameters:
      - name: username
        required: true
        in: path
        schema:
           type: string
      responses:
        "200":
           description: the user
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/User'

    get:
      operationId: app.get_user
      parameters:
      - name: username
        required: true
        in: path
        schema:
           type: string
      responses:
        "200":
           description: the user
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/User'


  /cast/{user}/{enemy}:
    post:
      operationId: app.post_cast
      parameters:
      - name: user
        required: true
        in: path
        schema:
           type: string
      - name: enemy
        required: true
        in: path
        schema:
          type: string
      summary: casts a spell
      x-body-name: body
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
           description: the server status
           content:
             application/json:
               schema: {}
components:
  schemas:
    Status:
      properties:
        users:
          type: array
          items:
            $ref: '#components/schemas/User'
        spells:
          type: object
    User:
      properties:
        name:
          type: string
        status:
          type: string
        last_spell:
          type: string
        ts:
          type: integer
        points:
          type: integer
        level:
          type: integer
        stats:
          type: object
