openapi: 3.0.1
info:
  title: potter
  version: 1beta
  contact:
    name: me
paths:
  /user/{username}:
    post:
      description: create a new user
      operationId: app.post_user
      parameters:
      - name: username
        required: true
        in: path
        schema:
           type: string
      responses:
        "200":
           description: the user
           content:
             application/json:
               schema: {}

    get:
      operationId: app.get_user
      parameters:
      - name: username
        required: true
        in: path
        schema:
           type: string
      responses:
        "200":
           description: the user
           content:
             application/json:
               schema: {}


  /cast/{user}/{enemy}:
    post:
      operationId: app.post_cast
      parameters:
      - name: user
        required: true
        in: path
        schema:
           type: string
      - name: enemy
        required: true
        in: path
        schema:
          type: string
      summary: casts a spell
      x-body-name: body
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
           description: the server status
           content:
             application/json:
               schema: {}
